### ISSUE TITLE
Sad state of Flow tooling

### ISSUE THREAD

**Issue by stereobooster** [stereobooster/type-o-rama#3]
- there are no decoder generators 📦, like for Elm Json.Decoders or TypeScript proxies. **UPD** [tried to use io-ts](https://github.com/transform-it/transform-json-types/pull/10) for this, but starting from version 1.0 `io-ts` dropped Flow support
- [`flow-typed install` is frustrating](https://github.com/flowtype/flow-typed/issues/1220)
- workflow around creating signatures is frustrating. You can generate definitions with `flow gen-flow-files` or `flow-typed create-stub` or you can create dinitions from TypeScript with `flowgen`, but it is so much effort to donate those signatures to `flow-typed` repo
- type errors can be really obscure and give no clue about what is wrong. Examples of how it supposed to be: [BetterErrors  for Reason](https://github.com/reasonml-old/BetterErrors) or Elm
- there is no tool which can convert Flow signatures to Closure JSDoc to use in Google Closure Compiler with advanced mode
- For type definitions distributed with packages to be picked up automatically, you need to include `node_modules` in analysis, which makes process painfully slow.

**Comment by stereobooster** [comment]
Good tools:
- [s2s](https://github.com/akameco/s2s)
- [glow](https://github.com/jamiebuilds/glow)
- [better errors in 0.66+](https://medium.com/flow-type/better-flow-error-messages-for-the-javascript-ecosystem-73b6da948ae2)
- [flow-coverage-report](https://github.com/rpl/flow-coverage-report)
- [validateDefs](https://github.com/flowtype/flow-typed/blob/master/cli/src/commands/validateDefs.js)
- [babel-plugin-transform-flow-to-gen](https://github.com/unbounce/babel-plugin-transform-flow-to-gen)
- [jest-runner-flowtype](https://www.npmjs.com/package/jest-runner-flowtype)
- [flowgen](https://github.com/joarwilk/flowgen) - good, but [unsupported](https://github.com/joarwilk/flowgen/issues/29) 
- [flow-typed](https://github.com/flowtype/flow-typed/) - good, but [development very slow](https://github.com/flowtype/flow-typed/issues/1494)

**Comment by stereobooster** [comment]
Projects that switched from Flow to TS:
- `redux-elm-skeleton` used to have flow branch, but as of now `redux-elm` renamed to `prism` and uses TypeScript
- `io-ts` starting from version 1.0

**Comment by laughedelic** [comment]
> Projects that switched from Flow to TS:

* https://github.com/atom/atom-languageclient/pull/175

**Comment by deepsweet** [comment]
Here is my "proof of concept of alternative Flow Library Definitions manager" https://github.com/deepsweet/flows

1. Library Definitions ("libdefs") are published as standalone packages with independent versions – whenever target dependency got major version bump there should be a major bump of libdefs as well
2. Flow version doesn't matter – when it doesn't work with the latest one then it's a bug
3. Target dependency version is specified in libdefs `package.json` as peer depehdency
4. `flows` CLI modifies `[libs]` in `.flowconfig` with libdefs dev dependencies found across root package and/or Yarn workspaces instead of copying files into special folder

What do you think?

My 2 cents about the sadness: it's even more sad when it comes to Node.js ecosystem outside of React world.

**Comment by stereobooster** [comment]
Hi @deepsweet, I haven't had a chance to test it yet. I'm so frustrated by Flow lately, that I suppose I have no choice except to switch to TypeScript (not ideal either) or Reason (a bit better).

Also there is https://github.com/yangshun/flow-scripts

**Comment by devCola** [comment]
coming from a TS side (current company decided to go with flow due to 'learning costs'...),
I think it would be better to have a ```@flowtype/<package-name>``` on npm.

TS had "typings" for managing typescript definitions from definitelytyped. 
But maintaining typings with its own infrastructure was quite a hassle. 
So TS got rid of typings and went for:

```npm install --save @types/react```

As a bonus on going for ```@types/<package-name>``` in npm, users just have to do ```yarn install```

ps: I'm absolutely abhorred about including all the flow-typed definitions on project repos...but that seems to be the only way :(
